# Generated by Django 3.0.7 on 2020-09-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountaboddiesapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
